server:
  port: 8082
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/temp?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
#    username: ${dbName}
#    password: ${dbPassword}
#    driver-class-name: com.mysql.jdbc.Driver