## transaction service group, server list, and other configurations
## vgroup_mapping.my_test_tx_group = "default"
## default.grouplist = "127.0.0.1:8091"
## enableDegrade = false
## disableGlobalTransaction = false

service {
  #vgroup->rgroup
  vgroup_mapping.my_test_tx_group = "default"
  #only support single node
  default.grouplist = "127.0.0.1:8091"
  #degrade current not support
  enableDegrade = false
  #disable
  disableGlobalTransaction = false
}
