registry {
  # file, nacos, eureka, redis, zk, consule, etcd3, sofa
  type = "file"

  file {
    name = "file.conf"
  }
}

config {
  # file, nacos, apollo, zk, consule, etcd3
  type = "file"

  file {
    name = "file.conf"
  }
}
